#!/bin/bash -l

#SBATCH -A g2021012
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 2:00:00
#SBATCH -J GenomeAnnotation
#SBATCH --mail-type=ALL
#SBATCH --mail-user Viktor.Sade.7837@student.uu.se

cp /proj/g2021012/2_Eckalbar_2016/additional_data/GCF_001595765.1_Mnat.v1_genomic.gff.gz ./
gunzip -f GCF_001595765.1_Mnat.v1_genomic.gff.gz
grep NW_015503979 GCF_001595765.1_Mnat.v1_genomic.gff > extracted.gff
